# Generated by Django 5.2.7 on 2025-10-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=255, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=255, unique=True, verbose_name='email address')),
                ('contact_number', models.CharField(max_length=100)),
                ('assigned_user', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('CA_image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('CB_image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('docs', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('experience', models.IntegerField(default='1')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('total_ratings', models.IntegerField(default=0)),
                ('cumulative_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], default='Electrician', max_length=50)),
                ('day', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('isFinished', models.CharField(default='No', max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('staff', models.CharField(default='Not assigned', max_length=50)),
                ('payment_status', models.CharField(default='Cash On Delivery', max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rated', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dispute_created', models.BooleanField(default=False)),
                ('dispute_resolved', models.BooleanField(default=False)),
                ('tier', models.CharField(default='bronze', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], default='Electrician', max_length=50)),
                ('day', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('isFinished', models.CharField(default='No', max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('staff', models.CharField(default='Not assigned', max_length=50)),
                ('payment_status', models.CharField(default='Cash On Delivery', max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('acknowledged', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback')], default='complaint', max_length=20)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/default_image.png', null=True, upload_to='images')),
                ('contact_number', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('credit_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_description', models.TextField()),
                ('business_category', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default='1')),
                ('image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('CA_image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('CB_image', models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images')),
                ('docs', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
