# Generated by Django 5.2.7 on 2025-11-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Cleaner', 'Cleaner')], default='Electrician', max_length=50),
        ),
        migrations.AlterField(
            model_name='deletedappointment',
            name='service',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Cleaner', 'Cleaner')], default='Electrician', max_length=50),
        ),
    ]
