# Generated by Django 5.2.7 on 2025-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
