# Generated by Django 5.2.7 on 2025-11-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_khalti_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_points',
        ),
    ]
